services:
  fellowship_db:
    image: postgres:18
    container_name: db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fellowship_app-db:/var/lib/postgresql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DATABASE_USERNAME} -d $${DATABASE_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  fellowship_app:
    # TODO: Image here should be updated when we have the real docker repository
    image: <INSERT IMAGE NAME HERE>:latest
    container_name: app
    depends_on:
      fellowship_db:
        condition: service_healthy
        restart: true
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static:/app/static
      - staticfiles:/app/staticfiles

volumes:
  fellowship_app-db:
  static:
  staticfiles:
