services:
  db:
    image: postgres:18
    container_name: db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fellowship_app-db:/var/lib/postgresql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DATABASE_USERNAME} -d $${DATABASE_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  fellowship_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - fellowship-dev:/fellowship-dev

volumes:
  fellowship_app-db:
  staticfiles:
  fellowship-dev:
