# BUILD STAGE
FROM python:3.13-slim AS builder

RUN mkdir /app

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# PRODUCTION STAGE
FROM python:3.13-slim

RUN useradd -m -r appuser && \
    mkdir /app && \
    mkdir /app/staticfiles &&\
    mkdir /app/static &&\
    mkdir /fellowship-dev && \
    chown -R appuser /app && \
    chown -R appuser /app/staticfiles && \
    chown -R appuser /app/static && \
    chown -R appuser /fellowship-dev

COPY --from=builder /usr/local/lib/python3.13/site-packages/ /usr/local/lib/python3.13/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/

WORKDIR /app

COPY --chown=appuser:appuer . .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

USER appuser

EXPOSE 8000

ENTRYPOINT ["./entrypoint-dev.sh"]
