# Generated by Django 6.0.5 on 2026-10-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.PositiveIntegerField()),
                ('author', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Author')),
                ('genres', models.ManyToManyField(related_name='books', to='books.genre', verbose_name='Genres')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('da', 'Danish'), ('en', 'English')], max_length=2)),
                ('original_language', models.BooleanField(verbose_name='Original language')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='books.seriescore')),
            ],
        ),
        migrations.CreateModel(
            name='BookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Subtitle')),
                ('cover_image', models.URLField(max_length=500, verbose_name='Cover image URL')),
                ('information_link', models.URLField(max_length=500, verbose_name='Information URL')),
                ('seller_link', models.URLField(max_length=500, verbose_name='Seller URL')),
                ('library_link', models.URLField(max_length=500, verbose_name='Library URL')),
                ('language', models.CharField(choices=[('da', 'Danish'), ('en', 'English')], max_length=2, verbose_name='Language')),
                ('original_language', models.BooleanField(verbose_name='Original language')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='books.bookcore', verbose_name='Core')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.seriesversion', verbose_name='Series')),
            ],
        ),
    ]
